name: Automatically update Node.js team release keys

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 12 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.repository_owner == 'nodejs'
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run automation script
        run: ./update-keys.sh

      - run: git diff
