name: Check Markdown links

on:
  pull_request:
    paths:
      - "**/*.md"
      - "markdown_link_check_config.json"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: tcort/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'
          config-file: 'markdown_link_check_config.json'
